### PR TITLE
Setup for server

### PR DESCRIPTION
**Pull request by nwhite89**
First setup for Static server.

When running to create simply go to
```
http://localhost:8080/create?html=<div>My HTML</div>
```

This will in turn return you an id going to this id will serve it once only
`http://localhost:8080/?id=<MY UNIQUE ID>`

to cache this file simply add a param of `&cache=true` to the above url

### CODE REVIEW

**Comment by facundfortuny** [comment]
Could you update the readme file with the steps how to set up it. And will necessary to add:
Create a tmp folder if this doesn't exist. 
Needs error handling, at the moment no messages is showed when error occurs.

**Comment by nwhite89** [comment]
Sure thing will get on it ASAP

**Comment by nwhite89** [comment]
@facundfortuny those points should now have been dealt with :smile: :+1:

**Comment by nwhite89** [comment]
does someone want to merge this @facundfortuny @jonman lol

**Comment by jaylett** [comment]
@facundfortuny @jonman please make a decision to either merge or delete :-)

**Pull request merged**
